# Generated by Django 3.1.7 on 2021-04-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTelegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=20)),
                ('numero_quantity', models.FloatField()),
                ('prix', models.FloatField()),
            ],
        ),
    ]
