# Generated by Django 3.1.7 on 2021-04-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_producttelegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttelegram',
            name='category',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
    ]
