# Generated by Django 3.1.7 on 2021-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_usertelegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertelegram',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
