# Generated by Django 3.1.7 on 2021-04-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_usertelegram_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertelegram',
            name='created_date',
        ),
    ]
