# Generated by Django 3.1.7 on 2021-04-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_usertelegram_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTelegram',
            new_name='UserTelegramTable',
        ),
    ]
