# Generated by Django 3.2 on 2021-05-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_docsinzip_doc_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='quantity_docs',
            field=models.IntegerField(db_index=True, default='-', verbose_name='кiл-ть док-тiв в архiвi'),
        ),
    ]
