# Generated by Django 3.2 on 2021-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_zip_quantity_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='date_fin',
            field=models.CharField(db_index=True, default='-', max_length=100, verbose_name='Дата завершення вибiрки YYYY-MM-DD'),
        ),
        migrations.AddField(
            model_name='zip',
            name='date_start',
            field=models.CharField(db_index=True, default='-', max_length=100, verbose_name='Дата початку вибiрки YYYY-MM-DD'),
        ),
    ]
