# Generated by Django 3.2 on 2021-05-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20210517_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='date_fin',
            field=models.DateField(default='2021-05-18', verbose_name='Дата завершення вибiрки'),
        ),
        migrations.AlterField(
            model_name='zip',
            name='date_start',
            field=models.DateField(default='2021-05-18', verbose_name='Дата початку вибiрки'),
        ),
    ]
