# Generated by Django 3.1.7 on 2021-04-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tele_magaz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTelegram',
            new_name='ProductTelegramTable',
        ),
    ]
