# Generated by Django 2.1.2 on 2021-04-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tele_magaz', '0003_auto_20210411_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttelegramtable',
            name='numero_quantity',
        ),
        migrations.AddField(
            model_name='producttelegramtable',
            name='etre',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttelegramtable',
            name='img',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttelegramtable',
            name='quantity',
            field=models.CharField(max_length=35),
        ),
    ]
