# Generated by Django 2.1.2 on 2021-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tele_magaz', '0004_auto_20210412_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttelegramtable',
            name='author',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
