# Generated by Django 2.1.2 on 2021-04-12 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tele_magaz', '0006_producttelegramtable_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
