# Generated by Django 2.1.2 on 2021-04-15 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tele_magaz', '0007_productcategorytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttelegramtable',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
