# Generated by Django 3.2 on 2021-04-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tele_magaz', '0008_producttelegramtable_modified_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategorytable',
            old_name='nom',
            new_name='category_nom',
        ),
    ]
