# Generated by Django 3.2 on 2021-04-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tele_magaz', '0009_rename_nom_productcategorytable_category_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategorytable',
            old_name='category_nom',
            new_name='nom',
        ),
    ]
