# Generated by Django 3.2 on 2021-05-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20210517_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsinzip',
            name='zip_numero',
            field=models.CharField(db_index=True, default='-', max_length=15, verbose_name='Zip_Numero'),
        ),
    ]
