# Generated by Django 3.2 on 2021-05-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_docsinzip_zip_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsinzip',
            name='doc_numero',
            field=models.IntegerField(db_index=True, default='-', verbose_name='Doc_Id'),
        ),
    ]
