# Generated by Django 3.2 on 2021-05-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20210517_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocsInZip',
        ),
    ]
